# Generated by Django 3.1.4 on 2020-12-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_no', models.CharField(max_length=50, unique=True)),
                ('home_phone', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=400, null=True)),
                ('photo', models.ImageField(upload_to='employee-photos/')),
                ('resume', models.ImageField(upload_to='employee-document/')),
                ('id_proof', models.ImageField(upload_to='employee-document/')),
                ('date_of_resignation', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.department')),
            ],
        ),
    ]
