# Generated by Django 3.1.4 on 2020-12-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
